version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: faucet
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: faucet
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
build:
  main: cmd/alignedlayerd
  ldflags:
    - "-r verifiers/sp1/lib"
