version: "3.2"

services:
  node-setup:
    image: alignedlayerd_i
    build:
      context: ../../
      dockerfile: ./Dockerfile
    volumes:
      - ../../prod-sim/${NODE_NAME}:/root/.alignedlayer
      - ../scripts/node.entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh ${NODE_NAME}

  validator-setup:
    image: alignedlayerd_i
    build:
      context: ../../
      dockerfile: ./Dockerfile
    volumes:
      - ../../prod-sim/${NODE_NAME}:/root/.alignedlayer
      - ../scripts/validator.entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh ${NODE_NAME} 1050000stake

  validator-runner:
    image: alignedlayerd_i
    build:
      context: ../../
      dockerfile: ./Dockerfile
    ports:
      - 26656:26656
      - 26657:26657
    volumes:
      - ../../prod-sim/${NODE_NAME}:/root/.alignedlayer
    command: start
